version: '3.8'
services:
  backend:
    build: .
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
      - DB_HOST=db
      - DB_USER=root
      - DB_PASSWORD=tu_password
      - DB_NAME=tu_base_de_datos
    depends_on:
      - db

  db:
    image: mysql:8
    environment:
      MYSQL_ROOT_PASSWORD: tu_password
      MYSQL_DATABASE: tu_base_de_datos
    ports:
      - "3306:3306"
